
collections:
# With the collection name, version, and source options
- name: sansoft.common_tasks
  type: git
  source: 'https://github.com/sandarenu/ansible_common_tasks_collection.git#/sansoft/common_tasks'